//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.18444
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IMI_BTRemote {
    using Gadgeteer;
    using GTM = Gadgeteer.Modules;
    
    
    public partial class Program : Gadgeteer.Program {
        
        private Gadgeteer.Modules.GHIElectronics.Display_T35 display_T35;
        
        private Gadgeteer.Modules.GHIElectronics.UC_Battery_4xAA uc_battery_4xAA;
        
        private Gadgeteer.Modules.GHIElectronics.Bluetooth bluetooth;
        
        public static void Main() {
            // Important to initialize the Mainboard first
            Program.Mainboard = new GHIElectronics.Gadgeteer.FEZSpider();
            Program p = new Program();
            p.InitializeModules();
            p.ProgramStarted();
            // Starts Dispatcher
            p.Run();
        }
        
        private void InitializeModules() {
            this.uc_battery_4xAA = new GTM.GHIElectronics.UC_Battery_4xAA(1);
            this.display_T35 = new GTM.GHIElectronics.Display_T35(14, 13, 12, 10);
            this.bluetooth = new GTM.GHIElectronics.Bluetooth(11);
        }
    }
}
